### ISSUE TITLE
Phrase Support

### ISSUE THREAD

**Issue by nickfogle** [Hexagon/thinker-fts#2]
Does this support word order of phrases?  For example, assume the text I want to search is 
"This is some sample text."

Is there any way to search for the phrase 'sample text' instead of 'sample' and 'text' in the sentence?

**Comment by nickfogle** [comment]
After reviewing the docs again, I now realize it's possible to achieve this using the `concatenateWords` setting.

**Comment by Hexagon** [comment]
Yes, exact phrase search isn't available as it would increase memory usage and/or slow down the queries. It might be added later as an optional feature, but for now I think the concatenateWords option is a reasonable workaround.
